In [1]:
import numpy as np
X_train = np.array([[ 1., -1.,  2.], [ 2.,  0.,  0.], [ 0.,  1., -1.]])

In [24]:
x1 = (X_train[:,0]-X_train[:,0].mean())/X_train[:,0].std()
x1

array([ 0.        ,  1.22474487, -1.22474487])

In [25]:
x2 = (X_train[:,1]-X_train[:,1].mean())/X_train[:,1].std()
x2

array([-1.22474487,  0.        ,  1.22474487])

In [26]:
x3 = (X_train[:,2]-X_train[:,2].mean())/X_train[:,2].std()
x3

array([ 1.33630621, -0.26726124, -1.06904497])

In [22]:
test = (X_train-X_train.mean(axis=0))/X_train.std(axis=0)
test

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [27]:
np.transpose(test) 

array([[ 0.        ,  1.22474487, -1.22474487],
       [-1.22474487,  0.        ,  1.22474487],
       [ 1.33630621, -0.26726124, -1.06904497]])

In [29]:
from sklearn import preprocessing
import numpy as np
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [30]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [31]:
X_scaled.std(axis = 0)

array([1., 1., 1.])

In [34]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [35]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [38]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [39]:
scaler.transform(X_train)    

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])